### PR TITLE
Add units to property names

### PR DESCRIPTION
**Pull request by m-mohr**
**Related Issue(s):** None

**Proposed Changes:**

Rename area to area_ha and perimeter to perimeter_m.

It was brought up yesterday that the properties could include the units to be more explicit.
We couldn't really decide so opening this for discussions (I think yesterday we had two no, two yes and some neutrals).
Please vote with thumbs up/down.

**PR Checklist:**

- [ ] This PR has **no** breaking changes.
- [x] I have added my changes to the [CHANGELOG](https://github.com/fiboa/specification/blob/dev/CHANGELOG.md)
  **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Comment by jacobsn** [comment]
A few thoughts:

- First, I don't care too much either way.
- But, IMHO there needs to be a strong argument in favor to make this change. I think the only argument in favor is essentially "it makes it a little easier to see what the units mean", but I think that's a minor short-term convenience and not something that would meaningfully change how likely people are to use the standard.
- If we are going to append units to every variable, I wonder if we'd end up with some cases where that's actually more confusing.
- Will this be a problem for any existing tools that rely on the current standard (visualization website, ...)?
- We'd have to change existing datasets, although if we are going to make this change we should do it now.

**Comment by m-mohr** [comment]
> * If we are going to append units to every variable, I wonder if we'd end up with some cases where that's actually more confusing.

That's a compelling argument to me. How would we expose slightly less "simple" units? Percent? $lm \cdot m^{−2}$ ...

**Comment by m-mohr** [comment]
@cholmes What's your feeling as the initiator of this idea? I tend towards closing this right now...

**Comment by cholmes** [comment]
Yeah, let's close it - just wanted to raise the discussion since it came up, but seems better to keep as it is.

**Pull request closed without merging**
